### ISSUE TITLE
报错config.json

### ISSUE THREAD

**Issue by Codethiefs** [eyblog/blog#3]
Error: ENOENT: no such file or directory, open '/Users/someone/Work/blog/src/common/config/config.json'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at global.readFile (/Users/someone/Work/blog/app/common/bootstrap/global.js:82:16)
    at _default.getConfig$ (/Users/someone/Work/blog/app/home/controller/base.js:34:147)
    at tryCatch (/Users/someone/Work/blog/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke](/Users/someone/Work/blog/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next](/Users/someone/Work/blog/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/someone/Work/blog/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at bound (domain.js:280:14)

**Comment by lscho** [comment]
嗯，当时设计问题，有一部分配置是写在/src/common/config/config.json中的，你新建一下这个文件就可以了。。
